version: 0.1.0.{build}

init:
  - set PACKAGE_PRERELEASE_SUFFIX=

build_script:
- build-appveyor.cmd

artifacts:
  - path: artifacts\*.nupkg
    name: nuget

deploy:
     # NuGet Deployment for releases
  - provider: NuGet
    server: 
    api_key:
      secure: fK6HViQb+42cziwzfw5OrwJG3LC6gl+NDLicTi2az4XwL6O0wqrdmDL7zmsB1787
    artifact: nuget
    on:
      branch: master
      appveyor_repo_tag: true